<a href="https://colab.research.google.com/github/ricardokendy/Test_Modeling_California_Housing/blob/main/modelingCaliforniaHolsing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
from sklearn import datasets
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np
from xgboost import XGBRegressor

In [2]:
housing = datasets.fetch_california_housing()


In [3]:
print(housing)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n-

In [4]:
df = pd.DataFrame(housing.data, columns = housing.feature_names)

In [5]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [6]:
housing.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [7]:
print(housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [8]:
print(housing.target)

[4.526 3.585 3.521 ... 0.923 0.847 0.894]


In [9]:
# CARACTERISTICAS DAS CASAS
X = housing.data

#PREÇO CONHECIDO DAS CASAS - TARGET
y = housing.target

# MODELING TECHNICS

1. Regressão Linear do SKLEARN
<https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression>
2. Suport Vector Regression do SKLEARN
<https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html#sklearn.svm.SVR>
3. Decision Tree Regression do XGBoost
<https://xgboost.readthedocs.io/en/stable/python/python_api.html>

Modeling Assumptions:

Apenas variáveis numéricas

#TEST DESIGN
## Dataset split:

Separação de Train/Test dataset padrão com 20% de massa para teste via método SKLEARN: <https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html#sklearn.model_selection.train_test_split>

#Métrica de avaliação do modelo:
Validação da métrica MSE(Mean Square Error) e RMSE(Root Mean Square Error) para penalizar grandes erros de previsão. Utilizando o método do SKLearn.
<https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html#sklearn.metrics.mean_squared_error>

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state=42)

In [11]:
print(X_train)
print(y_train)

[[   3.2596       33.            5.0176565  ...    3.6918138
    32.71       -117.03      ]
 [   3.8125       49.            4.47354497 ...    1.73809524
    33.77       -118.16      ]
 [   4.1563        4.            5.64583333 ...    2.72321429
    34.66       -120.48      ]
 ...
 [   2.9344       36.            3.98671727 ...    3.33206831
    34.03       -118.38      ]
 [   5.7192       15.            6.39534884 ...    3.17889088
    37.58       -121.96      ]
 [   2.5755       52.            3.40257649 ...    2.10869565
    37.77       -122.42      ]]
[1.03  3.821 1.726 ... 2.221 2.835 3.25 ]


TECNICA 1. REGRESSÃO LINEAR

In [12]:
regLinear = LinearRegression().fit(X_train,y_train)

In [13]:
yLinear = regLinear.predict(X_test)
print(yLinear)

[0.71912284 1.76401657 2.70965883 ... 4.46877017 1.18751119 2.00940251]


In [14]:
MSELinear = mean_squared_error(y_test, yLinear)

In [15]:
print('MSE Linear:',MSELinear)
print('RMSE Linear:',np.sqrt(MSELinear))

MSE Linear: 0.5558915986952422
RMSE Linear: 0.7455813830127749


TECNICA 2. SUPORT VECTOR REGRESSION (SVR)



In [16]:
regSVR = SVR().fit(X_train, y_train)

In [17]:
ySVR = regSVR.predict(X_test)

In [18]:
print(ySVR)

[1.74839687 1.77561334 1.88771095 ... 1.81632304 1.82315874 1.73570366]


In [19]:
MSE_SVR = mean_squared_error(y_test, ySVR)

In [20]:
print('MSE SVR:',MSE_SVR)
print('RMSE SVR:',np.sqrt(MSE_SVR))

MSE SVR: 1.3320115421348744
RMSE SVR: 1.1541280440812771


TECNICA 3. DECISION TREE REGRESSION (XGBoost)

In [21]:
regXGB = XGBRegressor().fit(X_train,y_train)

In [22]:
yXGB = regXGB.predict(X_test)

In [23]:
print(yXGB)

[0.5944522  0.7841187  5.1981163  ... 5.058281   0.76106036 1.8375903 ]


In [24]:
MSEXGB = mean_squared_error(y_test,yXGB)

In [25]:
print('MSE XGB:', MSEXGB)
print('RMSE XGB:', np.sqrt(MSEXGB))

MSE XGB: 0.2225899267544737
RMSE XGB: 0.4717943691423984


#OTIMIZAÇÃO DE HIPERPARAMETROS

Utilizando o metodo Grid SearchCV do SKLEARN
<https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#>


In [27]:
regXGB.get_params().keys()

dict_keys(['objective', 'base_score', 'booster', 'callbacks', 'colsample_bylevel', 'colsample_bynode', 'colsample_bytree', 'device', 'early_stopping_rounds', 'enable_categorical', 'eval_metric', 'feature_types', 'gamma', 'grow_policy', 'importance_type', 'interaction_constraints', 'learning_rate', 'max_bin', 'max_cat_threshold', 'max_cat_to_onehot', 'max_delta_step', 'max_depth', 'max_leaves', 'min_child_weight', 'missing', 'monotone_constraints', 'multi_strategy', 'n_estimators', 'n_jobs', 'num_parallel_tree', 'random_state', 'reg_alpha', 'reg_lambda', 'sampling_method', 'scale_pos_weight', 'subsample', 'tree_method', 'validate_parameters', 'verbosity'])

In [28]:
parameters = {
    "max_depth": [5,6,7],
    "learning_rate": [0.1,0.2,0.3],
    "objective":['reg:squarederror'],
    "booster":['gbtree'],
    "n_jobs":[5],
    "gamma":[0,1],
    "min_child_weight": [1,3],
    "max_delta_step": [0,1],
    "subsample": [0.5,1]

}


In [31]:
xgbGrid = GridSearchCV(XGBRegressor(),parameters, refit = 'neg_mean_squared_error', verbose=True)


In [32]:
xgbGridModel = xgbGrid.fit(X_train, y_train)

Fitting 5 folds for each of 144 candidates, totalling 720 fits


In [33]:
xgbGridModel.best_params_

{'booster': 'gbtree',
 'gamma': 0,
 'learning_rate': 0.2,
 'max_delta_step': 1,
 'max_depth': 7,
 'min_child_weight': 1,
 'n_jobs': 5,
 'objective': 'reg:squarederror',
 'subsample': 1}

In [34]:
yGrid = xgbGridModel. predict(X_test)

In [35]:
MSEGrid = mean_squared_error(y_test,yGrid)

In [37]:
print('MSE XGB Grid: ', MSEGrid)
print('RMSE XGB Grid: ', np.sqrt(MSEGrid))

MSE XGB Grid:  0.21638147438949515
RMSE XGB Grid:  0.4651682216032122
